// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pet_caring_website.Data;

#nullable disable

namespace Pet_caring_website.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250322103010_AdjustRoleGenderStatusToString")]
    partial class AdjustRoleGenderStatusToString
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "AppointmentStatus", new[] { "pending", "confirmed", "completed", "canceled" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "Gender", new[] { "male", "female" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "Role", new[] { "client", "vet", "admin" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Pet_caring_website.Models.Appointment", b =>
                {
                    b.Property<int>("ApId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ap_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("ApId"));

                    b.Property<DateOnly>("ApDate")
                        .HasColumnType("date")
                        .HasColumnName("ap_date");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("create_at");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("ApId")
                        .HasName("Appointments_pkey");

                    b.HasIndex("UserId");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("Pet_caring_website.Models.AppointmentDetail", b =>
                {
                    b.Property<int>("DetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("detail_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("DetailId"));

                    b.Property<int>("ApId")
                        .HasColumnType("integer")
                        .HasColumnName("ap_id");

                    b.Property<int>("PetId")
                        .HasColumnType("integer")
                        .HasColumnName("pet_id");

                    b.Property<int>("SvdId")
                        .HasColumnType("integer")
                        .HasColumnName("svd_id");

                    b.HasKey("DetailId")
                        .HasName("Appointment_Details_pkey");

                    b.HasIndex("ApId");

                    b.HasIndex("SvdId");

                    b.ToTable("Appointment_Details");
                });

            modelBuilder.Entity("Pet_caring_website.Models.Pet", b =>
                {
                    b.Property<int>("PetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("pet_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("PetId"));

                    b.Property<short>("Age")
                        .HasColumnType("smallint")
                        .HasColumnName("age");

                    b.Property<string>("Breed")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("breed");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("gender");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("PetName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("pet_name");

                    b.Property<short?>("SpcId")
                        .HasColumnType("smallint")
                        .HasColumnName("spc_id");

                    b.Property<decimal>("Weight")
                        .HasPrecision(10, 1)
                        .HasColumnType("numeric(10,1)")
                        .HasColumnName("weight");

                    b.HasKey("PetId")
                        .HasName("Pets_pkey");

                    b.HasIndex("SpcId");

                    b.ToTable("Pets");
                });

            modelBuilder.Entity("Pet_caring_website.Models.PetOwner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<int>("PetId")
                        .HasColumnType("integer")
                        .HasColumnName("pet_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("Pet_Owners_pkey");

                    b.HasIndex("PetId");

                    b.HasIndex("UserId");

                    b.ToTable("Pet_Owners");
                });

            modelBuilder.Entity("Pet_caring_website.Models.Service", b =>
                {
                    b.Property<short>("ServiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("service_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<short>("ServiceId"));

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("create_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasMaxLength(225)
                        .HasColumnType("character varying(225)")
                        .HasColumnName("service_name");

                    b.HasKey("ServiceId")
                        .HasName("Services_pkey");

                    b.ToTable("Services");
                });

            modelBuilder.Entity("Pet_caring_website.Models.ServiceDetail", b =>
                {
                    b.Property<int>("SvdId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("svd_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("SvdId"));

                    b.Property<short>("Amount")
                        .HasColumnType("smallint")
                        .HasColumnName("amount");

                    b.Property<short?>("Duration")
                        .HasColumnType("smallint")
                        .HasColumnName("duration");

                    b.Property<decimal>("PricePerService")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("price_per_service");

                    b.Property<short>("ServiceId")
                        .HasColumnType("smallint")
                        .HasColumnName("service_id");

                    b.HasKey("SvdId")
                        .HasName("Service_Detail_pkey");

                    b.HasIndex("ServiceId");

                    b.ToTable("Service_Detail");
                });

            modelBuilder.Entity("Pet_caring_website.Models.ServicePricing", b =>
                {
                    b.Property<short>("PricingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("pricing_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<short>("PricingId"));

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("create_at");

                    b.Property<decimal>("MaxWeight")
                        .HasPrecision(3, 2)
                        .HasColumnType("numeric(3,2)")
                        .HasColumnName("max_weight");

                    b.Property<decimal>("MinWeight")
                        .HasPrecision(3, 2)
                        .HasColumnType("numeric(3,2)")
                        .HasColumnName("min_weight");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("price");

                    b.Property<short>("ServiceId")
                        .HasColumnType("smallint")
                        .HasColumnName("service_id");

                    b.PrimitiveCollection<List<DateTime>>("UpdateAt")
                        .IsRequired()
                        .HasColumnType("timestamp with time zone[]")
                        .HasColumnName("update_at");

                    b.HasKey("PricingId")
                        .HasName("Service_Pricing_pkey");

                    b.HasIndex("ServiceId");

                    b.ToTable("Service_Pricing");
                });

            modelBuilder.Entity("Pet_caring_website.Models.Species", b =>
                {
                    b.Property<short>("SpcId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("spc_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<short>("SpcId"));

                    b.Property<string>("SpcName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("spc_name");

                    b.HasKey("SpcId")
                        .HasName("Species_pkey");

                    b.ToTable("Species");
                });

            modelBuilder.Entity("Pet_caring_website.Models.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("address");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("last_name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("password");

                    b.Property<string>("Phone")
                        .HasMaxLength(10)
                        .HasColumnType("character(10)")
                        .HasColumnName("phone")
                        .IsFixedLength();

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<string>("Speciality")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("speciality");

                    b.Property<string>("UserName")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("user_name");

                    b.HasKey("UserId")
                        .HasName("Users_pkey");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Pet_caring_website.Models.Appointment", b =>
                {
                    b.HasOne("Pet_caring_website.Models.User", "User")
                        .WithMany("Appointments")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("fk_appointments_users");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Pet_caring_website.Models.AppointmentDetail", b =>
                {
                    b.HasOne("Pet_caring_website.Models.Appointment", "Ap")
                        .WithMany("AppointmentDetails")
                        .HasForeignKey("ApId")
                        .IsRequired()
                        .HasConstraintName("fk_appointment_Details_appointments");

                    b.HasOne("Pet_caring_website.Models.ServiceDetail", "Svd")
                        .WithMany("AppointmentDetails")
                        .HasForeignKey("SvdId")
                        .IsRequired()
                        .HasConstraintName("fk_appoinment_Details_service_details");

                    b.Navigation("Ap");

                    b.Navigation("Svd");
                });

            modelBuilder.Entity("Pet_caring_website.Models.Pet", b =>
                {
                    b.HasOne("Pet_caring_website.Models.Species", "Spc")
                        .WithMany("Pets")
                        .HasForeignKey("SpcId")
                        .HasConstraintName("fk_pets_species");

                    b.Navigation("Spc");
                });

            modelBuilder.Entity("Pet_caring_website.Models.PetOwner", b =>
                {
                    b.HasOne("Pet_caring_website.Models.Pet", "Pet")
                        .WithMany("PetOwners")
                        .HasForeignKey("PetId")
                        .IsRequired()
                        .HasConstraintName("fk_owners_pets");

                    b.HasOne("Pet_caring_website.Models.User", "User")
                        .WithMany("PetOwners")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("fk_owners_users");

                    b.Navigation("Pet");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Pet_caring_website.Models.ServiceDetail", b =>
                {
                    b.HasOne("Pet_caring_website.Models.Service", "Service")
                        .WithMany("ServiceDetails")
                        .HasForeignKey("ServiceId")
                        .IsRequired()
                        .HasConstraintName("fk_service_detail_services");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("Pet_caring_website.Models.ServicePricing", b =>
                {
                    b.HasOne("Pet_caring_website.Models.Service", "Service")
                        .WithMany("ServicePricings")
                        .HasForeignKey("ServiceId")
                        .IsRequired()
                        .HasConstraintName("fk_service_pricing_services");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("Pet_caring_website.Models.Appointment", b =>
                {
                    b.Navigation("AppointmentDetails");
                });

            modelBuilder.Entity("Pet_caring_website.Models.Pet", b =>
                {
                    b.Navigation("PetOwners");
                });

            modelBuilder.Entity("Pet_caring_website.Models.Service", b =>
                {
                    b.Navigation("ServiceDetails");

                    b.Navigation("ServicePricings");
                });

            modelBuilder.Entity("Pet_caring_website.Models.ServiceDetail", b =>
                {
                    b.Navigation("AppointmentDetails");
                });

            modelBuilder.Entity("Pet_caring_website.Models.Species", b =>
                {
                    b.Navigation("Pets");
                });

            modelBuilder.Entity("Pet_caring_website.Models.User", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("PetOwners");
                });
#pragma warning restore 612, 618
        }
    }
}
